services:
  app:
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-karine_user}:${SERVICE_PASSWORD_64_POSTGRES}@karine-db:5432/${POSTGRES_DB:-karine_db}
    networks:
      - default
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.karine-https.redirectscheme.scheme=https
      - traefik.http.routers.karine-http.entrypoints=http
      - traefik.http.routers.karine-http.rule=Host(`karinemascena.com.br`) || Host(`www.karinemascena.com.br`) || Host(`147.79.110.132`)
      - traefik.http.routers.karine-http.middlewares=karine-https
      - traefik.http.routers.karine.entrypoints=https
      - traefik.http.routers.karine.rule=Host(`karinemascena.com.br`) || Host(`www.karinemascena.com.br`)
      - traefik.http.routers.karine.tls=true
      - traefik.http.routers.karine.tls.certresolver=letsencrypt
      - traefik.http.services.karine.loadbalancer.server.port=5000

  postgres:
    networks:
      default:
        aliases:
          - karine-db

networks:
  coolify:
    external: true
    name: coolify
